/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as HerbsIndexRouteImport } from './routes/herbs.index'
import { Route as HerbsHerbIdRouteImport } from './routes/herbs.$herbId'
import { Route as PointsIndexRouteImport } from './routes/points.index'
import { Route as PointsPointIdRouteImport } from './routes/points.$pointId'
import { Route as RoutinesIndexRouteImport } from './routes/routines.index'
import { Route as RoutinesRoutineIdRouteImport } from './routes/routines.$routineId'
import { Route as SystemsIndexRouteImport } from './routes/systems.index'
import { Route as SystemsSystemIdRouteImport } from './routes/systems.$systemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbsIndexRoute = HerbsIndexRouteImport.update({
  id: '/herbs/',
  path: '/herbs/',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbsHerbIdRoute = HerbsHerbIdRouteImport.update({
  id: '/herbs/$herbId',
  path: '/herbs/$herbId',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsIndexRoute = PointsIndexRouteImport.update({
  id: '/points/',
  path: '/points/',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsPointIdRoute = PointsPointIdRouteImport.update({
  id: '/points/$pointId',
  path: '/points/$pointId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoutineIdRoute = RoutinesRoutineIdRouteImport.update({
  id: '/routines/$routineId',
  path: '/routines/$routineId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSystemIdRoute = SystemsSystemIdRouteImport.update({
  id: '/systems/$systemId',
  path: '/systems/$systemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/saved': typeof SavedRoute
  '/herbs/$herbId': typeof HerbsHerbIdRoute
  '/points/$pointId': typeof PointsPointIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/herbs/': typeof HerbsIndexRoute
  '/points/': typeof PointsIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/saved': typeof SavedRoute
  '/herbs/$herbId': typeof HerbsHerbIdRoute
  '/points/$pointId': typeof PointsPointIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/herbs': typeof HerbsIndexRoute
  '/points': typeof PointsIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/systems': typeof SystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/saved': typeof SavedRoute
  '/herbs/$herbId': typeof HerbsHerbIdRoute
  '/points/$pointId': typeof PointsPointIdRoute
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/herbs/': typeof HerbsIndexRoute
  '/points/': typeof PointsIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/saved'
    | '/herbs/$herbId'
    | '/points/$pointId'
    | '/routines/$routineId'
    | '/systems/$systemId'
    | '/herbs/'
    | '/points/'
    | '/routines/'
    | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/saved'
    | '/herbs/$herbId'
    | '/points/$pointId'
    | '/routines/$routineId'
    | '/systems/$systemId'
    | '/herbs'
    | '/points'
    | '/routines'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/saved'
    | '/herbs/$herbId'
    | '/points/$pointId'
    | '/routines/$routineId'
    | '/systems/$systemId'
    | '/herbs/'
    | '/points/'
    | '/routines/'
    | '/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  SavedRoute: typeof SavedRoute
  HerbsHerbIdRoute: typeof HerbsHerbIdRoute
  PointsPointIdRoute: typeof PointsPointIdRoute
  RoutinesRoutineIdRoute: typeof RoutinesRoutineIdRoute
  SystemsSystemIdRoute: typeof SystemsSystemIdRoute
  HerbsIndexRoute: typeof HerbsIndexRoute
  PointsIndexRoute: typeof PointsIndexRoute
  RoutinesIndexRoute: typeof RoutinesIndexRoute
  SystemsIndexRoute: typeof SystemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herbs/': {
      id: '/herbs/'
      path: '/herbs'
      fullPath: '/herbs/'
      preLoaderRoute: typeof HerbsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herbs/$herbId': {
      id: '/herbs/$herbId'
      path: '/herbs/$herbId'
      fullPath: '/herbs/$herbId'
      preLoaderRoute: typeof HerbsHerbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/': {
      id: '/points/'
      path: '/points'
      fullPath: '/points/'
      preLoaderRoute: typeof PointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/$pointId': {
      id: '/points/$pointId'
      path: '/points/$pointId'
      fullPath: '/points/$pointId'
      preLoaderRoute: typeof PointsPointIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/$routineId': {
      id: '/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof RoutinesRoutineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$systemId': {
      id: '/systems/$systemId'
      path: '/systems/$systemId'
      fullPath: '/systems/$systemId'
      preLoaderRoute: typeof SystemsSystemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  SavedRoute: SavedRoute,
  HerbsHerbIdRoute: HerbsHerbIdRoute,
  PointsPointIdRoute: PointsPointIdRoute,
  RoutinesRoutineIdRoute: RoutinesRoutineIdRoute,
  SystemsSystemIdRoute: SystemsSystemIdRoute,
  HerbsIndexRoute: HerbsIndexRoute,
  PointsIndexRoute: PointsIndexRoute,
  RoutinesIndexRoute: RoutinesIndexRoute,
  SystemsIndexRoute: SystemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
